apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konlateang-front-end
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.frontend.port }}